name: Drew Pluta
favicon: null
layout_spectrum: 0.7491
typography_spectrum: 0.21612
title: Drew Pluta Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#210c10'
    - '#e9f2ee'
    - '#5b2d46'
    - '#a2afaa'
    - '#a47354'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
